import fs from 'node:fs';
import path from 'node:path';
import { copyDir, ensureDir, exists, listFiles, readText, relativeToCwd, removeDir, sha256, timestamp, writeText } from './fs-utils.js';
import { expandProfile, lockfilePath, runtimeDir } from './manifest.js';
import { loadModules, readFragment } from './modules.js';

export function installRuntime(manifest, profile, root) {
  const moduleNames = expandProfile(manifest, profile);
  const modules = loadModules(manifest, moduleNames, root);
  const output = runtimeDir(manifest, profile, root);
  const lockfile = lockfilePath(manifest, root);
  detectNameConflicts(modules, manifest);

  removeDir(output);
  ensureDir(output);
  ensureDir(path.join(output, 'skills'));
  ensureDir(path.join(output, 'agents'));
  ensureDir(path.join(output, 'prompts'));

  const agents = generateAgentsMarkdown(profile, modules);
  writeText(path.join(output, 'AGENTS.generated.md'), agents);
  writeText(path.join(output, 'AGENTS.md'), agents);
  writeText(path.join(output, 'config.toml'), generateConfigToml(manifest, profile, modules));

  for (const module of modules) {
    copyDir(path.join(module.dir, 'skills'), path.join(output, 'skills'));
    copyDir(path.join(module.dir, 'agents'), path.join(output, 'agents'));
    copyDir(path.join(module.dir, 'prompts'), path.join(output, 'prompts'));
    copyDir(path.join(module.dir, 'templates'), path.join(output, 'templates', module.name));
    const mcp = path.join(module.dir, 'mcp.toml');
    if (exists(mcp)) writeText(path.join(output, 'mcp', `${module.name}.toml`), readText(mcp));
  }

  const metadata = {
    generatedAt: timestamp(),
    profile,
    materialization: manifest.runtime?.materialization || 'copy',
    globalConfigChanged: false,
    instructionActivation: 'runtime AGENTS.md plus AGENTDEPS_AGENTS_PATH; current Codex surfaces may require an agent to inspect this file explicitly',
    modules: modules.map(({ name, version, hash, capabilityClasses, skills, agents, mcp }) => ({ name, version, hash, capabilityClasses, skills, agents, mcp }))
  };
  writeText(path.join(output, 'metadata.json'), `${JSON.stringify(metadata, null, 2)}\n`);

  const generatedFiles = listFiles(output)
    .sort()
    .map((file) => ({ path: path.relative(output, file), sha256: sha256(fs.readFileSync(file)) }));
  writeText(lockfile, generateLockToml(profile, modules, output, generatedFiles));

  return { profile, output, lockfile, modules, generatedFiles };
}

function generateAgentsMarkdown(profile, modules) {
  const body = modules.map((module) => {
    const fragment = readFragment(module);
    return [`## Module: ${module.name}`, fragment || '_No instruction fragment._'].join('\n\n');
  }).join('\n\n---\n\n');
  return `# Generated AgentDeps Instructions\n\nGenerated for profile: ${profile}\n\nDo not hand-edit this file. Regenerate with \`mad install --profile ${profile}\`.\n\n${body}\n`;
}

function generateConfigToml(manifest, profile, modules) {
  const moduleList = modules.map((module) => module.name).join(', ');
  return `# Generated by AgentDeps. Do not hand-edit.\n\n[agentdeps]\nprofile = "${profile}"\nmodules = "${moduleList}"\nglobal_config_changed = false\n\n# MCP fragments, when present, are copied under ./mcp/*.toml for inspection.\n# AgentDeps v0 does not promise live MCP hot reload.\n`;
}

function generateLockToml(profile, modules, output, generatedFiles) {
  const lines = [
    '# Generated by AgentDeps. Do not hand-edit.',
    '',
    '[lock]',
    'version = 1',
    `generated_at = "${timestamp()}"`,
    `profile = "${profile}"`,
    `runtime = "${relativeToCwd(output)}"`,
    'global_config_changed = false',
    ''
  ];
  modules.forEach((module, index) => {
    lines.push(`[[modules]]`);
    lines.push(`name = "${module.name}"`);
    lines.push(`version = "${module.version}"`);
    lines.push(`hash = "${module.hash}"`);
    lines.push(`capability_classes = [${module.capabilityClasses.map((item) => JSON.stringify(item)).join(', ')}]`);
    if (index !== modules.length - 1) lines.push('');
  });
  lines.push('', '[generated]');
  lines.push(`count = ${generatedFiles.length}`);
  generatedFiles.forEach((file) => {
    lines.push('', '[[generated.files]]');
    lines.push(`path = ${JSON.stringify(file.path)}`);
    lines.push(`sha256 = ${JSON.stringify(file.sha256)}`);
  });
  return `${lines.join('\n')}\n`;
}

function detectNameConflicts(modules, manifest) {
  if (manifest.policy?.fail_on_name_conflict === false) return;
  const seen = new Map();
  const conflicts = [];
  for (const module of modules) {
    for (const area of ['skills', 'agents', 'prompts']) {
      const base = path.join(module.dir, area);
      for (const file of listFiles(base)) {
        const key = `${area}/${path.relative(base, file)}`;
        const owner = seen.get(key);
        if (owner && owner !== module.name) conflicts.push(`${key} from ${owner} and ${module.name}`);
        else seen.set(key, module.name);
      }
    }
    const mcp = path.join(module.dir, 'mcp.toml');
    if (exists(mcp)) {
      const key = `mcp/${module.name}.toml`;
      const owner = seen.get(key);
      if (owner && owner !== module.name) conflicts.push(`${key} from ${owner} and ${module.name}`);
      else seen.set(key, module.name);
    }
  }
  if (conflicts.length) throw new Error(`capability name conflicts detected:\n- ${conflicts.join('\n- ')}`);
}
